decidim/decidim-bulletin-board

.github/workflows/app-workflow.yml
.github/workflows/js-workflow.yml
.github/workflows/ruby-workflow.yml
.gitignore
decidim-bulletin_board-app/Gemfile
decidim-bulletin_board-app/Gemfile.lock
decidim-bulletin_board-app/spec/rails_helper.rb

This PR configures the code coverage gem and adds it to the project PRs workflow.

Add code coverage for tests

---

.devcontainer/Dockerfile
decidim-bulletin_board-app/app/models/bulletin_board.rb
decidim-bulletin_board-app/app/models/client.rb
decidim-bulletin_board-app/app/models/concerns/has_public_key.rb
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.js
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.test.js
decidim-bulletin_board-js/src/trustee/__mocks__/trustee.js
decidim-bulletin_board-js/src/trustee/trustee.js
decidim-bulletin_board-js/src/trustee/trustee_wrapper_dummy.js
decidim-bulletin_board-js/src/trustee/trustee_wrapper_dummy.test.js

This PR allows the key ceremony process to continue from a previous process, without sending duplicated messages to the Bulletin Board.

Improve wrapper state handling

---

decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/close_ballot_box.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/open_ballot_box.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/client.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/close_ballot_box_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/open_ballot_box_spec.rb

This PR adds the methods for opening and closing the ballot box to the Bulletin Board client.

Open and close ballot box from authority

---

decidim-bulletin_board-ruby/CHANGELOG.md
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/bb_schema.json
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/version.rb

This PR updates the schema definition with the log entries retrieval filter.

Update GraphQL schema definition

---

decidim-bulletin_board-app/app/assets/javascripts/sandbox/key_ceremony.es6
decidim-bulletin_board-app/app/assets/javascripts/sandbox/tally.es6
decidim-bulletin_board-js/src/index.js
decidim-bulletin_board-js/src/tally/tally.component.js
decidim-bulletin_board-ruby/CHANGELOG.md

This adds a new class called `TallyComponent` that will help integrating the tally process in any UI. I used this class in the sandbox environment and it will be used in `decidim` in a future upgrade.

feat: add the Tally component

---

.github/workflows/app-workflow.yml
.gitignore
decidim-bulletin_board-app/Gemfile
decidim-bulletin_board-app/Gemfile.lock
decidim-bulletin_board-app/config/initializers/cypress_on_rails.rb
decidim-bulletin_board-app/config/routes.rb
decidim-bulletin_board-app/package-lock.json
decidim-bulletin_board-app/package.json
decidim-bulletin_board-app/spec/cypress.json
decidim-bulletin_board-app/spec/cypress/app_commands/activerecord_fixtures.rb
decidim-bulletin_board-app/spec/cypress/app_commands/clean.rb
decidim-bulletin_board-app/spec/cypress/app_commands/eval.rb
decidim-bulletin_board-app/spec/cypress/app_commands/factory_bot.rb
decidim-bulletin_board-app/spec/cypress/app_commands/log_fail.rb
decidim-bulletin_board-app/spec/cypress/app_commands/scenarios/list_elections.rb
decidim-bulletin_board-app/spec/cypress/cypress_helper.rb
decidim-bulletin_board-app/spec/cypress/fixtures/example.json
decidim-bulletin_board-app/spec/cypress/integration/sandbox/list_elections.page.js
decidim-bulletin_board-app/spec/cypress/integration/sandbox/list_elections.spec.js
decidim-bulletin_board-app/spec/cypress/plugins/index.js
decidim-bulletin_board-app/spec/cypress/support/commands.js
decidim-bulletin_board-app/spec/cypress/support/index.js
decidim-bulletin_board-app/spec/cypress/support/on-rails.js
decidim-bulletin_board-app/yarn.lock

This setup the e2e test suite for our bulletin board application. It will test our sandbox environment, so we can be sure that both the JS and the Ruby clients work.
I added a simple test as an example, so we can start building something on top of that.

test: install cypress_on_rails and add a simple test as an example

---

decidim-bulletin_board-app/app/assets/javascripts/sandbox/vote.es6
decidim-bulletin_board-js/jest.config.js
decidim-bulletin_board-js/src/index.js
decidim-bulletin_board-js/src/setupTests.js
decidim-bulletin_board-js/src/vote/vote.component.js
decidim-bulletin_board-js/src/voter/voter.js
decidim-bulletin_board-js/src/voter/voter.test.js
decidim-bulletin_board-js/src/voter/voter_wrapper_dummy.js
decidim-bulletin_board-ruby/CHANGELOG.md

This adds a new class called `VoteComponent` that will help integrating the vote process in any UI. I used this class in the sandbox environment and it will be used in `decidim` in a future upgrade.

feat: add Vote component

---

.github/workflows/app-workflow.yml
decidim-bulletin_board-app/app/assets/config/manifest.js
decidim-bulletin_board-app/app/assets/javascripts/sandbox/tally.es6
decidim-bulletin_board-app/app/assets/stylesheets/sandbox/tally.scss
decidim-bulletin_board-app/app/views/sandbox/elections/tally.html.erb
decidim-bulletin_board-app/spec/cypress/integration/sandbox/election.page.js
decidim-bulletin_board-app/spec/cypress/integration/sandbox/election.spec.js

This is built on top of #94, and it adds the tally process to the whole test. I also refactored some things to make the test less flaky 👍

test: add the tally process to the e2e test

---

decidim-bulletin_board-app/app/assets/stylesheets/api/docs.scss
decidim-bulletin_board-app/app/controllers/pages_controller.rb
decidim-bulletin_board-app/app/javascript/packs/application.js
decidim-bulletin_board-app/app/views/layouts/application.html.erb
decidim-bulletin_board-app/app/views/pages/index.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/index.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/key_ceremony.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/tally.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/vote.html.erb
decidim-bulletin_board-app/config/routes.rb
decidim-bulletin_board-app/install_eg_wrappers.sh
decidim-bulletin_board-app/package-lock.json
decidim-bulletin_board-app/package.json
decidim-bulletin_board-app/yarn.lock

This PR adds an index page to improve the BB server navigation

add home page and use docs design everywhere

---

decidim-bulletin_board-app/app/assets/javascripts/sandbox/vote.es6
decidim-bulletin_board-app/app/assets/stylesheets/sandbox/vote.scss
decidim-bulletin_board-app/app/controllers/sandbox/elections_controller.rb
decidim-bulletin_board-app/app/views/sandbox/elections/vote.html.erb
decidim-bulletin_board-app/spec/cypress/integration/sandbox/election.page.js
decidim-bulletin_board-app/spec/cypress/integration/sandbox/election.spec.js
decidim-bulletin_board-js/src/vote/vote.component.js
decidim-bulletin_board-js/src/voter/voter.js
decidim-bulletin_board-js/src/voter/voter.test.js
decidim-bulletin_board-js/src/voter/voter_wrapper_dummy.js
decidim-bulletin_board-js/src/voter/voter_wrapper_dummy.test.js
decidim-bulletin_board-ruby/CHANGELOG.md

This PR adds the "audit vote" option after encrypting a ballot.
https://user-images.githubusercontent.com/19774772/107549888-a2955f80-6bd0-11eb-9be1-385734e1103a.mov

Audit vote

---

decidim-bulletin_board-app/README.md

This PR adds the two (_actually, it's only one besides the normal start of the server_) commands to the app README.

Update README with sandbox instructions

---

decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/vote/vote.component.js
decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/voter/voter-wrapper-adapter.js
decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/voter/voter.js
decidim-bulletin_board-app/app/javascript/packs/sandbox/vote.js
voting-scheme-dummy/src/voter_wrapper.js
voting-scheme-dummy/src/voter_wrapper_adapter.js
voting-scheme-election_guard/src/index.js
voting-scheme-election_guard/src/trustee_wrapper_adapter.js
voting-scheme-election_guard/src/voter_wrapper_adapter.js
voting-scheme-election_guard/src/wrapper_adapter.js

This applies the same pattern that we saw in #109. The idea is to extract the `election_guard` voting scheme part from the voter and use an adapter.

Add the VoterWrapperAdapter for the election_guard scheme

---

decidim-bulletin_board-app/app/views/pages/index.html.erb
decidim-bulletin_board-app/config/routes.rb

Allow to set an environment variable to use the sandbox on the staging server.

Activate sandbox if required

---

.gitignore
voting-scheme-election_guard/package-lock.json
voting-scheme-election_guard/package.json
voting-scheme-election_guard/webpack.config.js

Add the build script for the election guard voting scheme.

chore: add build script to the voting scheme election_guard

---

.gitignore
decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/vote/vote.component.js
voting-scheme-election_guard/package-lock.json
voting-scheme-election_guard/package.json
voting-scheme-election_guard/webpack.config.js

We need to wait until the `onCastBallot` has finished before showing the cast complete message.

fix: wait until cast succeed to call the correct callback

---

decidim-bulletin_board-app/app/commands/concerns/log_entry_command.rb
decidim-bulletin_board-app/app/commands/process_key_ceremony_step.rb
decidim-bulletin_board-app/app/commands/process_tally_step.rb
decidim-bulletin_board-app/app/commands/start_key_ceremony.rb
decidim-bulletin_board-app/app/commands/start_tally.rb
decidim-bulletin_board-app/app/services/voting_scheme/dummy.rb
decidim-bulletin_board-app/app/services/voting_scheme/election_guard.rb

* Depends on https://github.com/decidim/decidim-electionguard/pull/11

Wrappers return a list of messages instead of a single message

---

decidim-bulletin_board-app/app/controllers/sandbox/elections_controller.rb
decidim-bulletin_board-app/app/javascript/packs/sandbox/vote.js
decidim-bulletin_board-app/app/services/voting_scheme/dummy.rb
decidim-bulletin_board-app/app/views/sandbox/elections/index.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/results.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/vote.html.erb
decidim-bulletin_board-app/config/routes.rb
decidim-bulletin_board-app/cypress/integration/sandbox/election.page.js
decidim-bulletin_board-app/cypress/integration/sandbox/election.spec.js
voting-scheme-dummy/src/voter_wrapper.js
voting-scheme-dummy/src/voter_wrapper_adapter.js

This PR adds the results page to the sandbox. It also adds a check to the E2E tests to verify that the results are calculated correctly.

Results page on the sandbox

---

decidim-bulletin_board-app/app/javascript/packs/sandbox/vote.js
decidim-bulletin_board-app/app/views/sandbox/elections/vote.html.erb

This PR adds a message with the encryption time to the vote page in the BB sandbox.

Add a message with the encryption time to the vote sandbox

---

.devcontainer/Dockerfile
bulletin_board/js-client/src/vote/vote.component.js
bulletin_board/server/app/assets/config/manifest.js
bulletin_board/server/app/assets/javascripts/sandbox/in_person_vote.js
bulletin_board/server/app/assets/javascripts/sandbox/index.js
bulletin_board/server/app/assets/javascripts/sandbox/vote.js
bulletin_board/server/app/assets/stylesheets/application.css
bulletin_board/server/app/assets/stylesheets/sandbox/elections/new.scss
bulletin_board/server/app/assets/stylesheets/sandbox/in_person_vote.scss
bulletin_board/server/app/assets/stylesheets/sandbox/index.scss
bulletin_board/server/app/assets/stylesheets/sandbox/key_ceremony.scss
bulletin_board/server/app/assets/stylesheets/sandbox/results.scss
bulletin_board/server/app/assets/stylesheets/sandbox/tally.scss
bulletin_board/server/app/assets/stylesheets/sandbox/vote.scss
bulletin_board/server/app/controllers/sandbox/elections_controller.rb
bulletin_board/server/app/helpers/sandbox/elections_helper.rb
bulletin_board/server/app/views/sandbox/elections/in_person_vote.html.erb
bulletin_board/server/app/views/sandbox/elections/index.html.erb
bulletin_board/server/app/views/sandbox/elections/key_ceremony.html.erb
bulletin_board/server/app/views/sandbox/elections/new.html.erb
bulletin_board/server/app/views/sandbox/elections/results.html.erb
bulletin_board/server/app/views/sandbox/elections/tally.html.erb
bulletin_board/server/app/views/sandbox/elections/vote.html.erb
bulletin_board/server/config/routes.rb
bulletin_board/server/cypress/integration/sandbox/election.page.js
bulletin_board/server/cypress/integration/sandbox/election.spec.js
bulletin_board/server/package-lock.json
bulletin_board/server/package.json

This PR implements the "in person" vote in the sandbox. 
It also fixes some issues we had in the sandbox:
* It improves a bit the design consistency.
* It allows to select several answers for a question.
* If fixes a bug with the "encrypt" button (it was opening a new tab when pressed).
* If fixes the stress tests buttons, that weren't working.
* It checks the result of the casting of the vote in the BB server (asks for the status of the pending message).

Complete sandbox with "in person" vote

---

voting_schemes/electionguard/python-wrapper/Pipfile.lock

This fixes some problems in the python wrapper dependencies 👍

Fix python wrapper dependencies

---

bin/verify

This adds a simple binary that will be used to verify either an election or a ballot. 
```sh
bin/verify <my_election_or_ballot_file_path>
```

Add the verify binary

---

.github/workflows/server-workflow.yml
Dockerfile.release
Dockerfile.web
Dockerfile.worker
bulletin_board/server/Gemfile
bulletin_board/server/Gemfile.lock
bulletin_board/server/app/controllers/sandbox/elections_controller.rb
bulletin_board/server/app/jobs/sandbox/generate_votes_job.rb
bulletin_board/server/app/services/voting_scheme/electionguard/voter.rb
bulletin_board/server/app/views/sandbox/elections/index.html.erb
bulletin_board/server/config/environments/production.rb
bulletin_board/server/config/initializers/redis.rb
bulletin_board/server/config/initializers/sidekiq.rb
bulletin_board/server/config/routes.rb
bulletin_board/server/config/sidekiq.yml
docker-entrypoint-worker.sh

Adapts the Bulletin Board sandbox to ease stress test execution.
- Adds a Dockerfile for the worker server;
- Enables Sidekiq in prod environment;
- Uploads the generated votes CSV to transfer.sh and writes the URL and the upload time in Redis;
- Creates a new `VoterAdapter` for each generated vote to simulate votes from different voters.

Prepare bulletin board for load test

---

Makefile
voting_schemes/electionguard/docker/ruby-node-python-electionguard/Makefile

This PR fixes and adds some tasks to ease the deployment process.

Fix deploy process
