.github/workflows/app-workflow.yml
.github/workflows/client-ruby-workflow.yml
README.md
decidim-bulletin-board-client-ruby/.gitignore
decidim-bulletin-board-client-ruby/.rspec
decidim-bulletin-board-client-ruby/.travis.yml
decidim-bulletin-board-client-ruby/CODE_OF_CONDUCT.md
decidim-bulletin-board-client-ruby/Gemfile
decidim-bulletin-board-client-ruby/Gemfile.lock
decidim-bulletin-board-client-ruby/LICENSE.txt
decidim-bulletin-board-client-ruby/README.md
decidim-bulletin-board-client-ruby/Rakefile
decidim-bulletin-board-client-ruby/bin/console
decidim-bulletin-board-client-ruby/bin/setup
decidim-bulletin-board-client-ruby/decidim-bulletin_board.gemspec
decidim-bulletin-board-client-ruby/lib/decidim/bulletin_board.rb
decidim-bulletin-board-client-ruby/lib/decidim/bulletin_board/client.rb
decidim-bulletin-board-client-ruby/lib/decidim/bulletin_board/version.rb
decidim-bulletin-board-client-ruby/spec/decidim/bulletin_board_spec.rb
decidim-bulletin-board-client-ruby/spec/spec_helper.rb

This adds a new project to the repository in the folder `decidim-bulletin-board-client-ruby`. This folder will include the `decidim-bulletin_board` gem.
I just created a new gem using the `bundle` command and it is meant to be used in upcoming PRs to move some logic from the `decidim` project to here.

Create decidim-bulletin-board gem scaffold

---

decidim-bulletin-board-client-js/jest.config.js
decidim-bulletin-board-client-js/package-lock.json
decidim-bulletin-board-client-js/package.json
decidim-bulletin-board-client-js/src/client/__mocks__/graphql-client.js
decidim-bulletin-board-client-js/src/client/client.js
decidim-bulletin-board-client-js/src/client/client.test.js
decidim-bulletin-board-client-js/src/client/graphql-client.js
decidim-bulletin-board-client-js/src/client/graphql-client.test.js
decidim-bulletin-board-client-js/src/client/operations/get_election_log_entries.gql
decidim-bulletin-board-client-js/src/client/operations/process_key_ceremony_step.gql
decidim-bulletin-board-client-js/src/client/operations/subscribe_to_election_log.gql
decidim-bulletin-board-client-js/src/index.js
decidim-bulletin-board-client-js/src/index.test.js
decidim-bulletin-board-client-js/src/setupTests.js

This adds a new class `Client` to the package that will be used to interact with the GraphQL API in the Bulletin Board application. It can be used like this:
```js
import { Client } from "decidim-bulletin_board";
const bulletinBoardClient = new Client({
apiEndpointUrl: "http://localhost:8000/api",
wsEndpointUrl: "ws://localhost:8000/cable",
headers: {
Authorization: "some-token"
}
});
bulletinBoardClient.getElectionLogEntries({ electionId: "dummy.1" });
```
The `Client` class is just a facade and it uses a `GraphQLClient` class that perform the operations to the GraphQL schema. I included some tests for both classes but at the moment the `GraphQLClient` just include some simple ones because it is a bit difficult to mock the websockets interactions.
This class will be used in upcoming PRs …

feat(js): add Client class to interact with the Bulletin Board

---

decidim-bulletin-board-app/Gemfile
decidim-bulletin-board-app/Gemfile.lock
decidim-bulletin-board-app/config/initializers/cors.rb
decidim-bulletin-board-app/config/settings.yml

This adds the `rack-cors` gem to allow AJAX requests form a different domain. By default it only allows `localhost:3000` since it is the domain used for the `decidim` application in development.
In production environments a suitable domain must be provided using the `CORS_ORIGIN_ALLOWED` environment variable.

chore(app): allow AJAX requests from different domains

---

decidim-bulletin-board-client-js/package-lock.json
decidim-bulletin-board-client-js/package.json
decidim-bulletin-board-client-js/src/client/client.js
decidim-bulletin-board-client-js/src/client/graphql-client.js
decidim-bulletin-board-client-js/src/index.js
decidim-bulletin-board-client-js/src/key-ceremony/key-ceremony.js
decidim-bulletin-board-client-js/src/key-ceremony/key-ceremony.test.js
decidim-bulletin-board-client-js/src/trustee/__mocks__/jwt_parser.js
decidim-bulletin-board-client-js/src/trustee/__mocks__/trustee.js
decidim-bulletin-board-client-js/src/trustee/__mocks__/trustee_wrapper_dummy.js
decidim-bulletin-board-client-js/src/trustee/jwt_parser.js
decidim-bulletin-board-client-js/src/trustee/trustee.js
decidim-bulletin-board-client-js/src/trustee/trustee.test.js
decidim-bulletin-board-client-js/src/trustee/trustee_wrapper_dummy.js

This adds the `KeyCeremony` class that can be used to perform the key ceremony in `decidim`. It works like this:
```js
import { Client, KeyCeremony } from "decidim-bulletin_board";
const bulletinBoardClient = new Client({...});
const keyCeremony = new KeyCeremony({
bulletinBoardClient,
electionContext: {...}
});
// This is the current API and doesn't support notifications yet.
// Also this may change in upcoming PRs.
await keyCeremony.setup();
const result = await keyCeremony.run();
```
At the moment it only works with the dummy voting schema included in the Bulletin Board application and not exactly. I changed a few things in the current dummy schema but they are not included in this PR to simplify things.
I also left the JWT signature verification to another PR to make the review …

feat(js): add KeyCeremony class

---

decidim-bulletin-board-app/app/commands/create_election.rb
decidim-bulletin-board-app/app/commands/process_key_ceremony_step.rb
decidim-bulletin-board-app/app/services/voting_scheme/dummy.rb
decidim-bulletin-board-app/spec/commands/process_key_ceremony_step_spec.rb

This changes the `Dummy` voting scheme to store the trustee ids so it only returns the final message when all trustees have sent their keys.
It also fixes a minor 🐛 bug when the trustee public keys were not stored as JSON objects. This caused an issue while decoding the data.

fix(app): store trustee ids in the scheme state

---

decidim-bulletin_board-js/package-lock.json
decidim-bulletin_board-js/src/index.test.js
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.js
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.test.js

This adds a simple `events` observable to the `KeyCeremony` class. As a user of the library now I can do this:
```js
const keyCeremony = new KeyCeremony(...);
keyCeremony.events.subscribe(event => {
// do something with the event
});
```
At the moment there are just two events supported: `MESSAGE_RECEIVED` and `MESSAGE_PROCESSED`. These two events can be exported from the key ceremony module as well:
```js
const { MESSAGE_RECEIVED, MESSAGE_PROCESSED } = decidimBulletinBoard.KeyCeremony;
```
This can be useful to update the UI accordingly in case you are expecting some messages to be processed.

feat: add key ceremony events observable

---

decidim-bulletin_board-app/app/commands/concerns/has_message_identifier.rb
decidim-bulletin_board-app/app/commands/concerns/log_entry_command.rb
decidim-bulletin_board-app/app/commands/create_election.rb
decidim-bulletin_board-app/app/commands/enqueue_message.rb
decidim-bulletin_board-app/app/commands/process_key_ceremony_step.rb
decidim-bulletin_board-app/app/jobs/process_key_ceremony_step_job.rb
decidim-bulletin_board-app/app/models/pending_message.rb
decidim-bulletin_board-app/db/migrate/20201201141644_change_pending_messages_election_null.rb
decidim-bulletin_board-app/db/schema.rb
decidim-bulletin_board-app/spec/commands/enqueue_message_spec.rb
decidim-bulletin_board-app/spec/commands/process_key_ceremony_step_spec.rb
decidim-bulletin_board-app/spec/factories/models.rb
decidim-bulletin_board-app/spec/jobs/process_key_ceremony_step_job_spec.rb
decidim-bulletin_board-app/spec/models/pending_message_spec.rb
decidim-bulletin_board-app/spec/mutations/process_key_ceremony_step_mutation_spec.rb

After adding the identifiers to the messages we can get the election identifier without having to decode the signed message. So, its better to assign the election to the pending messages before enqueueing them to be processed. This PR implements this.

Save election with pending messages

---

decidim-bulletin_board-app/app/graphql/types/log_entry_type.rb
decidim-bulletin_board-app/spec/queries/get_election_log_entries_spec.rb
decidim-bulletin_board-js/src/client/graphql-client.test.js
decidim-bulletin_board-js/src/client/operations/get_election_log_entries.gql
decidim-bulletin_board-js/src/client/operations/subscribe_to_election_log.gql
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.test.js
decidim-bulletin_board-js/src/trustee/__mocks__/trustee.js
decidim-bulletin_board-js/src/trustee/trustee.js
decidim-bulletin_board-js/src/trustee/trustee.test.js
decidim-bulletin_board-js/src/trustee/trustee_wrapper_dummy.js
decidim-bulletin_board-ruby/spec/fixtures/bb_schema.json

This deprecated the `logType` field since it has been replaced by the `messageId`.

chore: deprecate logType for log entries

---

decidim-bulletin_board-app/app/commands/concerns/log_entry_command.rb
decidim-bulletin_board-app/app/commands/create_election.rb
decidim-bulletin_board-app/app/commands/process_key_ceremony_step.rb
decidim-bulletin_board-app/app/commands/vote.rb
decidim-bulletin_board-app/app/models/authority.rb
decidim-bulletin_board-app/app/models/bulletin_board.rb
decidim-bulletin_board-app/app/models/client.rb
decidim-bulletin_board-app/app/models/trustee.rb
decidim-bulletin_board-app/spec/commands/create_election_spec.rb
decidim-bulletin_board-app/spec/commands/process_key_ceremony_step_spec.rb
decidim-bulletin_board-app/spec/commands/vote_spec.rb
decidim-bulletin_board-app/spec/models/authority_spec.rb
decidim-bulletin_board-app/spec/models/trustee_spec.rb

This PR validates that the command is called by the correct Client and also ensures that the message author is the expected, otherwise it broadcast an `:invalid`.

Validate client type and message author in commands

---

.github/workflows/app-workflow.yml
.github/workflows/js-workflow.yml
.github/workflows/ruby-workflow.yml

Current Github Actions configuration only run tests for the folders modified by the commits of the last push. This prevents executing the right tests if you push a new commit not affecting a folder modified in the previous commits of the same PR.
This PR changes this, executing the tests for all the folders modified by the PR, and running all the tests when pushing the changes to `master`.

Run all tests affected by PR

---

decidim-bulletin_board-app/app/graphql/types/log_entry_type.rb
decidim-bulletin_board-app/app/graphql/types/pending_message_type.rb
decidim-bulletin_board-app/app/graphql/types/query_type.rb
decidim-bulletin_board-app/app/models/log_entry.rb
decidim-bulletin_board-app/db/migrate/20201207160752_add_content_hash_to_log_entries.rb
decidim-bulletin_board-app/db/schema.rb
decidim-bulletin_board-app/spec/factories/models.rb
decidim-bulletin_board-app/spec/queries/get_log_entry_spec.rb
decidim-bulletin_board-app/spec/queries/get_pending_message_spec.rb
decidim-bulletin_board-js/src/types.d.ts
decidim-bulletin_board-ruby/spec/fixtures/bb_schema.json

This PR adds the content hash field to log entries and allow clients to retrieve a log entry by its content hash. This feature will be used to implement the vote verification described in decidim/decidim#5975. 
It also adds the `messageId` field to the PendingMessage GraphQL type and a test for the `pendingMessage` query.

Add support for vote verification

---

decidim-bulletin_board-js/src/voter/__mocks__/voter_wrapper_dummy.js
decidim-bulletin_board-js/src/voter/voter.js
decidim-bulletin_board-js/src/voter/voter.test.js
decidim-bulletin_board-js/src/voter/voter_wrapper_dummy.js
decidim-bulletin_board-ruby/Gemfile.lock
decidim-bulletin_board-ruby/decidim-bulletin_board.gemspec
decidim-bulletin_board-ruby/lib/decidim/bulletin_board.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/client.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/version.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/voter.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/voter/cast_vote.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/voter/vote_form.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/client_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/voter/cast_vote_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/voter/vote_form_spec.rb
decidim-bulletin_board-ruby/spec/spec_helper.rb

In this PR I am gonna enhance the `decidim-bulletin_board` npm package and the `decidim-bulletin_board` gem to include the business logic necessary to vote.
I decided to split the work in different PRs and merging everything in this one.
- Add the `Voter` and `VoterWrapper` (dummy) classes https://github.com/decidim/decidim-bulletin-board/commit/ae50a9745c4734a3cfde544d6b271db89e6985ec
- Cast vote from the Ruby client using the `cast_vote` method. https://github.com/decidim/decidim-bulletin-board/pull/30
- Bump decidim-bulletin_board v0.2.0 https://github.com/decidim/decidim-bulletin-board/pull/25/commits/43f249d27cc4a5fce06ebdee1fb0617a6a955ca2

Add Voter to the Bulletin Board client

---

decidim-bulletin_board-js/src/index.js
decidim-bulletin_board-js/src/voter/voter_wrapper_dummy.js
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/version.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/voter/vote_form.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/voter/vote_form_spec.rb

This PR releases the v0.2.1 version of the gem with a small patch. In the `VoteForm` I assumed the `encrypted_vote` data was passed as a Ruby `Hash` but after a technical discussion we decided to stick to JSON for now.
I also added the `iat` attribute that was missing and made clear what is the message that we are signing.
For the JS part I fixed a small bug where I forgot to export the `Voter` class and finally decided to change the dummy implementation of that encrypt to return a JSON. This will simplify the `decidim` part as well.

fix: cast vote content changes

---

decidim-bulletin_board-ruby/CHANGELOG.md

This adds a `CHANGELOG.md` file to the `decidim-bulletin_board` to keep track of the changes. I included the changes from the upcoming `v0.3.0` version as well that will be released after merging this.

chore: add changelog to the decidim-bulletin_board gem

---

decidim-bulletin_board-ruby/CHANGELOG.md
decidim-bulletin_board-ruby/Gemfile.lock
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/client.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/version.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/client_spec.rb

This fixes the `sign_data` method to use the correct private key. I also added the missing test to catch the 🐛

fix: sign data was not using the correct private key to sign

---

.devcontainer/Dockerfile

The `apt` version of nodejs doesn't include `npm`, so this PR change that to use its last stable version.

Update version of nodejs for dev containers

---

decidim-bulletin_board-app/Gemfile.lock
decidim-bulletin_board-app/app/commands/concerns/log_entry_command.rb
decidim-bulletin_board-app/app/commands/create_election.rb
decidim-bulletin_board-app/app/models/log_entry.rb
decidim-bulletin_board-app/app/services/voting_scheme/dummy.rb
decidim-bulletin_board-app/db/migrate/20201207160752_add_content_hash_to_log_entries.rb
decidim-bulletin_board-app/db/schema.rb
decidim-bulletin_board-app/spec/commands/process_key_ceremony_step_spec.rb
decidim-bulletin_board-app/spec/commands/shared/log_entry_validations.rb
decidim-bulletin_board-app/spec/commands/vote_spec.rb
decidim-bulletin_board-app/spec/factories/messages.rb
decidim-bulletin_board-app/spec/jobs/process_key_ceremony_step_job_spec.rb
decidim-bulletin_board-app/spec/jobs/vote_job_spec.rb
decidim-bulletin_board-app/spec/mutations/vote_mutation_spec.rb
decidim-bulletin_board-js/src/client/message-identifier.js
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.js
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.test.js
decidim-bulletin_board-js/src/trustee/__mocks__/trustee.js
decidim-bulletin_board-js/src/trustee/trustee_wrapper_dummy.js

While connecting the JS client with the BB we detected some inconsistencies in the messages format that needs to be addressed. So, we have defined a new message format, isolating the keys used by the BB and the information handled by the wrappers, like this:
```json
{
"iat": 123456,
"message_id": "decidim-barcelona.1.key_ceremony.trustee_election_keys+t.trustee-1",
"content": "here goes the wrapper information"
}
```
This way, is possible to calculate the SHA for the content generated by the wrapper before completing and signing the message.
This PR apply the new format in the bulletin board application and also to the key ceremony part of the JS client.

New messages format

---

decidim-bulletin_board-js/src/client/__mocks__/graphql-client.js
decidim-bulletin_board-js/src/client/client.js
decidim-bulletin_board-js/src/client/client.test.js
decidim-bulletin_board-js/src/client/graphql-client.js
decidim-bulletin_board-js/src/client/graphql-client.test.js
decidim-bulletin_board-js/src/client/operations/get_log_entry.gql

This PR adds a method to the JS client to use the endpoint implemented in #29 to retrieve a log entry using the hash of the log entry content.

Add a JS client method to get a LogEntry by hash

---

decidim-bulletin_board-js/src/client/message-identifier.js
decidim-bulletin_board-js/src/index.js
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.js

This PR exports the `MessageIdentifier` to be used in the `key_cermeony` process on Decidim. It also adds the `backup` method of the `TrusteeWrapper` to `KeyCeremony` to be used directly on Decidim calling the `key_ceremony`.

Refactor bulletin board JS client

---

decidim-bulletin_board-ruby/CHANGELOG.md
decidim-bulletin_board-ruby/Gemfile.lock
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/client.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/version.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/client_spec.rb

This PR fixes some errors of the 0.5.0 version and updates the changelog.
- Include the missing `close_ballot_box` method from the 0.4.0 release.
- Fixes for the client methods

Release version 0.5.1

---

decidim-bulletin_board-app/Gemfile
decidim-bulletin_board-app/Gemfile.lock
decidim-bulletin_board-app/config/settings.yml
decidim-bulletin_board-app/db/seeds.rb
decidim-bulletin_board-app/lib/tasks/client/generate_schema.rake
decidim-bulletin_board-app/spec/factories/models.rb

This PR updates the gem version used by the app and make changes requiered for that version. It also allow all CORS origins on the dev enviroment to simplify the testing of the Decidim Elections module. Finally, it creates tests elections with very high unique IDs, to avoid collisions with elections created on the Decidim dev app.

Misc changes for the app

---

decidim-bulletin_board-ruby/Gemfile.lock
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/client.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/version.rb

When using the gem in the app, it doesn't load the schema right. This PR fixes that, using absolute paths for the json file path.

Fix graphql schema file location

---

decidim-bulletin_board-app/app/commands/concerns/log_entry_command.rb
decidim-bulletin_board-app/app/commands/enqueue_message.rb
decidim-bulletin_board-app/app/commands/open_ballot_box.rb
decidim-bulletin_board-app/app/commands/process_key_ceremony_step.rb
decidim-bulletin_board-app/app/commands/vote.rb
decidim-bulletin_board-app/app/jobs/process_key_ceremony_step_job.rb

This PR tries to fix the errors raised when triggering events inside transaction, as sometimes the receiver code can't access to the rows created in the transaction until this is commited.

Fix notifier errors

---

.devcontainer/devcontainer.json
decidim-bulletin_board-app/app/commands/concerns/log_entry_command.rb
decidim-bulletin_board-app/app/commands/enqueue_message.rb
decidim-bulletin_board-app/app/commands/open_ballot_box.rb
decidim-bulletin_board-app/app/commands/process_key_ceremony_step.rb
decidim-bulletin_board-app/app/commands/vote.rb
decidim-bulletin_board-app/app/graphql/types/log_entry_type.rb
decidim-bulletin_board-app/app/jobs/process_key_ceremony_step_job.rb
decidim-bulletin_board-app/app/jobs/vote_job.rb
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.js
decidim-bulletin_board-js/src/types.d.ts
decidim-bulletin_board-js/src/voter/voter.js
decidim-bulletin_board-ruby/CHANGELOG.md
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/client.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/bb_schema.json

This PR adds the verify vote method to the voter client. 
Also, it allows the contentHash to be null on the GraphQL types, to support returning the messages without a `content` key. 
Finally, it updates the changelog, includes the prettier extension in the dev containers and updates the changelog with some missing changes.

Add verify vote and get the vote process working

---

decidim-bulletin_board-app/app/graphql/types/election_type.rb
decidim-bulletin_board-app/app/graphql/types/log_entry_type.rb
decidim-bulletin_board-app/config/environments/development.rb

This PR allow JS client to request only the last log entries of an election, allowing to use polling instead of GraphQL subscriptions.

Support for request only the last log entries of an election

---

decidim-bulletin_board-app/db/seeds.rb
decidim-bulletin_board-app/spec/factories/messages.rb

I wanted to test the Tally client, and then I realized that our seeds are missing some log entries. I decided to enhance them to include more log entries in an election depending on the status. This will help to test things in the sandbox that I am building here #68 
https://user-images.githubusercontent.com/106021/105348879-3a62e780-5be9-11eb-90a1-f2fa808df00e.mov

chore: enhance seeds to include more log entries

---

decidim-bulletin_board-js/src/client/graphql-client.js
decidim-bulletin_board-js/src/election/election.js
decidim-bulletin_board-js/src/election/election.test.js
decidim-bulletin_board-js/src/index.js
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.js
decidim-bulletin_board-js/src/key-ceremony/key-ceremony.test.js
decidim-bulletin_board-js/src/trustee/__mocks__/trustee.js
decidim-bulletin_board-js/src/trustee/__mocks__/trustee_wrapper_dummy.js
decidim-bulletin_board-js/src/trustee/trustee.js
decidim-bulletin_board-js/src/trustee/trustee.test.js
decidim-bulletin_board-js/src/trustee/trustee_wrapper_dummy.js
decidim-bulletin_board-js/src/trustee/trustee_wrapper_dummy.test.js
decidim-bulletin_board-ruby/CHANGELOG.md

This is the first step to implement the Tally in #67. I wanted to refactor our current codebase to make it easier. Since the `CHANGELOG.md` include all the changes I am going to paste it below.
This PR include some breaking changes that will be addressed in `decidim` after releasing a new version of the gem.
- The `KeyCeremony` class no longer receives an `electionContext` but an `election` object.
- The `KeyCeremony` class now receives a `trustee` object.
- `checkRestoreNeeded` method has been renamed to `needsToBeRestored` for both the `Trustee` and the `TrusteeWrapper`.
- The `Trustee` class now uses the `Election` class to interact with the log entries.
- `Election` class in the JS package to handle the election state. An instance of this class will be used by the key ceremony and the …

refactor(js): add Election class and refactor key ceremony

---

decidim-bulletin_board-js/src/voter/voter_wrapper_dummy.js
decidim-bulletin_board-ruby/CHANGELOG.md

This PR adds a Timeout of 500ms to the `encrypt` method of the Voter Dummy to be more realistic.

chore: add timeout to encrypt method

---

decidim-bulletin_board-app/Gemfile.lock

This PR updates the `decidim-bulletin_board` gem for the app to version 0.8.2

chore: update gem 0.8.2

---

decidim-bulletin_board-app/app/javascript/packs/application.js
decidim-bulletin_board-app/package-lock.json
decidim-bulletin_board-app/package.json
decidim-bulletin_board-app/yarn.lock

When deploying the BB app to heroku the `rake assets:precompile` failed because of the `babel/polyfill` package is deprecated this PR removes the dependency and as the babel docs suggest replaces the polyfill with `core-js/stable` and `regenerator-runtime/runtime` -> https://babeljs.io/docs/en/babel-polyfill.

fix(app): remove deprecated babel/polyfill

---

decidim-bulletin_board-app/app/commands/enqueue_message.rb
decidim-bulletin_board-js/src/client/client.js
decidim-bulletin_board-js/src/client/client.test.js
decidim-bulletin_board-js/src/client/graphql-client.test.js
decidim-bulletin_board-js/src/voter/voter.js
decidim-bulletin_board-ruby/CHANGELOG.md
decidim-bulletin_board-ruby/Gemfile.lock
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/create_election.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/end_vote.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/get_election_status.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/publish_results.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/start_key_ceremony.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/start_tally.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/start_vote.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/client.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/command.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/voter/cast_vote.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/create_election_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/end_vote_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/publish_results_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/start_key_ceremony_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/start_tally_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/start_vote_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/client_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/command_spec.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/voter/cast_vote_spec.rb
decidim-bulletin_board-ruby/spec/spec_helper.rb
decidim-bulletin_board-ruby/spec/support/command_stub.rb

This PR generalize two things done in the `cast_vote` to use them on the admin side:
* Ruby: Most of the client operations yield the `message_id` before sending the command to the BB server.
* JS: The method to wait for a pending message to be processed was moved from the `Voter` class to the `Client`, to use it in the admin zone too.

feat: apply pending message checking for votes to admin actions

---

decidim-bulletin_board-app/app/views/documentation/show.html.erb

This PR fixes the BB version showed in the `api/docs` page, it also fixes the path to `graphiql`.

Fix BulletinBoard version and graphiql path in `api/docs`

---

decidim-bulletin_board-app/app/commands/enqueue_message.rb
decidim-bulletin_board-app/app/graphql/types/log_entry_type.rb
decidim-bulletin_board-app/app/services/voting_scheme/dummy.rb
decidim-bulletin_board-app/db/seeds.rb
decidim-bulletin_board-app/spec/factories/messages.rb
decidim-bulletin_board-app/spec/factories/models.rb
decidim-bulletin_board-js/src/types.d.ts
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/bb_schema.json

This PR implements some fixes to the BB app:
* It fixes the calculation of the results of an election with the dummy voting scheme.
* It allows to enqueue several pending messages for the same client, if they don't have the same `message_id`.
* It fixes the seeding process to use the right election keys for the trustees and to sign correctly the messages sent by the BB.
* It adds the `decodedData` field to the graphQL interface to ease the debugging of the messages.

Fix dummy schema results calculations & other fixes

---

decidim-bulletin_board-app/app/assets/stylesheets/api/docs.scss
decidim-bulletin_board-app/app/commands/create_election.rb
decidim-bulletin_board-app/app/controllers/sandbox/elections_controller.rb
decidim-bulletin_board-app/app/graphql/decidim_bulletin_board_schema.rb
decidim-bulletin_board-app/app/graphql/types/election_type.rb
decidim-bulletin_board-app/app/views/sandbox/elections/index.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/key_ceremony.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/new.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/tally.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/vote.html.erb
decidim-bulletin_board-app/config/routes.rb
decidim-bulletin_board-app/db/migrate/20210211173543_change_elections_title_type.rb
decidim-bulletin_board-app/db/schema.rb
decidim-bulletin_board-app/spec/factories/models.rb
decidim-bulletin_board-app/spec/mutations/create_election_mutation_spec.rb
decidim-bulletin_board-js/src/types.d.ts
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/bb_schema.json

This PR adds the `create_election` command to be tested in the sandbox. It also changes the election title field to a `jsonb` column to be able to store different translations for that text.

Allow to create elections on the sandbox

---

decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/vote/vote.component.js
decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/voter/voter.js
decidim-bulletin_board-app/app/javascript/packs/sandbox/vote.js
decidim-bulletin_board-app/app/views/sandbox/elections/vote.html.erb
decidim-bulletin_board-app/cypress/integration/sandbox/election.page.js
decidim-bulletin_board-app/cypress/integration/sandbox/election.spec.js
decidim-bulletin_board-app/package-lock.json
decidim-bulletin_board-ruby/CHANGELOG.md
voting-scheme-dummy/src/voter_wrapper_adapter.js

With this PR, the `ballot_hash` is available after `encrypting` the vote. Therefore, it can be displayed before deciding to `audit` or `cast` a vote.

Get ballot hash before auditing or casting

---

decidim-bulletin_board-app/app/commands/create_election.rb
decidim-bulletin_board-app/spec/factories/messages.rb
decidim-bulletin_board-ruby/CHANGELOG.md

The `create_election` command now expects objects representing the parts public keys.

Use objects to represent JWKs everywhere

---

decidim-bulletin_board-app/install_eg_wrappers.sh

Improves the install ElectionGuard wrapper script with: 
* Better portability with /usr/bin/env shebang 
* -e for "Exit immediately if a command exits with a non-zero status."
* I had an error with my python3 installation (_ctypes module). I could solve it with the `libffi-dev` apt package
* Instead of using relative routes (../../) use /tmp/ folder
* Checks existence of the repository before removing it
* Change commets to echo to give more feedback to users

Cleanup the install_eg_wrappers.sh script

---

decidim-bulletin_board-app/app/commands/concerns/log_entry_command.rb
decidim-bulletin_board-app/app/services/voting_scheme/election_guard.rb

This PR fixes a problem we had when processing the electionguard wrappers results. When we get nested `dict`s from python, it was only converting to hash the main object, but not the nested `dict`s. With this changes, this conversion is only done in the `electionguard` service, and it's done recursively.

Convert dicts to hashes recursively

---

decidim-bulletin_board-app/app/services/voting_scheme/election_guard.rb

All the processed messages must return a hash and we made a mistake with the `start_tally` one.

fix: start tally must return a hash

---

decidim-bulletin_board-app/app/controllers/sandbox/elections_controller.rb
decidim-bulletin_board-app/app/graphql/types/log_entry_type.rb
decidim-bulletin_board-app/app/graphql/types/message_interface.rb
decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/types.d.ts
decidim-bulletin_board-app/app/models/concerns/message.rb
decidim-bulletin_board-app/app/views/sandbox/elections/new.html.erb
decidim-bulletin_board-app/spec/queries/get_election_log_entries_spec.rb
decidim-bulletin_board-app/spec/services/voting_scheme_spec.rb
decidim-bulletin_board-ruby/CHANGELOG.md
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/create_election.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/bb_schema.json
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/create_election_spec.rb

This PR fixes two issues:
* For ElectionGuard, the `sequenceOrder` cannot have the same value for two questions or two answers in the same question. Instead of using the weight, this PR makes the create election to use the `sequenceOrder` based on the order in the list where the questions and answers are in the `electionData` parameters.
* In the GraphQL API, when the `signedData` was hidden, the `decodedData` were still visible. This PR fixes that.

Fix sequence order and hiding decodedData for results

---

decidim-bulletin_board-app/app/commands/concerns/log_entry_command.rb

This PR adds the `message_id` and removes the `message_type` from the `signedData` field on the BB messages. This enhances the consistency between different messages.

Replace message_type with message_id on the BB messages

---

decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/key-ceremony/key-ceremony.component.js
decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/tally/tally.component.js
decidim-bulletin_board-app/app/javascript/decidim-bulletin_board/vote/vote.component.js
decidim-bulletin_board-app/app/javascript/packs/sandbox/key_ceremony.js
decidim-bulletin_board-app/app/javascript/packs/sandbox/tally.js
decidim-bulletin_board-app/app/javascript/packs/sandbox/vote.js
decidim-bulletin_board-app/app/views/sandbox/elections/vote.html.erb
decidim-bulletin_board-app/cypress/integration/sandbox/election.page.js

We are removing the `onSetup` event so before performing any action with the wrapper adapter we are going wait for the setup to be done.
With this change, the UI is not responsible to enable the button in the appropriate moment.

feat: remove onSetup event and wait for setup to perform actions

---

decidim-bulletin_board-app/app/assets/stylesheets/sandbox/vote.scss
decidim-bulletin_board-app/app/controllers/sandbox/elections_controller.rb
decidim-bulletin_board-app/app/javascript/packs/sandbox/vote.js
decidim-bulletin_board-app/app/views/sandbox/elections/vote.html.erb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/client.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/file_client.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/factory.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/file_adapter.rb

Adds a "Store vote to file" button to the sandbox that allows to write the vote's GraphQL request to a CSV file.
On the JS side, to avoid touching the library, we're binding the new button to the same events as "Cast ballot" and [setting a global variable to know which of the buttons has been clicked](https://github.com/decidim/decidim-bulletin-board/pull/132/files#diff-6b6dc1d14767f3dc0fe9429248dc49e46229ccefc48fbfdb290261cf89aee7d4R98-R100). This information is then sent to the controller.
On the ruby gem side, we added a [new client to the factory](https://github.com/decidim/decidim-bulletin-board/pull/132/files#diff-bbc31b0d371b259d6e80a1e1de811ab7df05d73fe3d7f4769ea6772118048332R18-R25) that employs a newly crafted adapter to store the request to a file in CSV format ([here are the …

Store vote requests to file from sandbox

---

decidim-bulletin_board-app/config/environments/development.rb

add github codespaces host to `development` environment.
Before this was the error
```
Blocked host: xxxxxxx.apps.codespaces.githubusercontent.com To allow requests to xxxxxxx.apps.codespaces.githubusercontent.com
```

add codespaces to config.hosts

---

decidim-bulletin_board-app/app/assets/config/manifest.js
decidim-bulletin_board-app/app/assets/stylesheets/application.css
decidim-bulletin_board-app/app/assets/stylesheets/sandbox/index.scss
decidim-bulletin_board-app/app/assets/stylesheets/sandbox/vote.scss
decidim-bulletin_board-app/app/controllers/sandbox/elections_controller.rb
decidim-bulletin_board-app/app/javascript/packs/sandbox/index.js
decidim-bulletin_board-app/app/javascript/packs/sandbox/vote.js
decidim-bulletin_board-app/app/views/sandbox/elections/index.html.erb
decidim-bulletin_board-app/app/views/sandbox/elections/vote.html.erb
decidim-bulletin_board-app/config/routes.rb

Allows generating a user-defined number of votes encrypted with the dummy schema, replicating https://github.com/decidim/decidim-bulletin-board/blob/develop/voting_schemes/dummy/js-adapter/src/voter_wrapper.js#L78.
The votes are stored in a CSV file that will later be used by JMeter.
For the moment being, the logic is in the controller and does not check what schema the election uses.
When introducing support to the EG schema these things will be addressed.
In my local machine, it takes about 20 second per 1000 votes.
[bulk votes](https://user-images.githubusercontent.com/5033945/109857627-2fc15680-7c5b-11eb-8ed1-53e3cbf6c82d.mov)

Generate bulk votes from sandbox - dummy schema

---

decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/file_adapter.rb

The CSV generated in #136 needed manual adjustments (double `"` around strings in JSON) to be read by JMeter.
Now using the standard CSV ruby gem that outputs in a format directly processable by JMeter.

Fix bulk vote CSV format

---

.gitignore
decidim-bulletin_board-app/app/assets/stylesheets/sandbox/index.scss
decidim-bulletin_board-app/app/controllers/sandbox/elections_controller.rb
decidim-bulletin_board-app/app/javascript/packs/sandbox/index.js
decidim-bulletin_board-app/app/views/sandbox/elections/index.html.erb
decidim-bulletin_board-app/config/environments/development.rb
decidim-bulletin_board-app/config/routes.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/graphql/file_adapter.rb

Adds the possibility to download the generated votes CSV from a button in the sandbox.
**Disclaimer**: Heroku timeouts requests over 30s, so it's not possible to generate more than ~1000 votes with the current method.
For the moment I'll just manually merge several files, but if we want to automatise the load test we'll need to move the file generation to a background job.
[](https://user-images.githubusercontent.com/5033945/110104401-67d5b000-7da7-11eb-8f70-2c88b18f1e53.mov)
Also: moves `require "test/private_keys"` to the sandbox controller to have it available in all environments

Add download button for bulk votes

---

.github/workflows/app-workflow.yml
.github/workflows/ruby-workflow.yml
.github/workflows/verifier-workflow.yml
.github/workflows/voting-scheme-dummy-js-adapter-workflow.yml
.github/workflows/voting-scheme-election_guard-js-adapter-workflow.yml
.github/workflows/voting-scheme-election_guard-python-wrapper-workflow.yml
README.md
decidim-bulletin_board-app/.rubocop.yml
docs/modules/develop/pages/environment.adoc

Some github actions and documentation files were linking to the `master` branch, which was renamed to `main` some time ago. In particular, code coverage was not being calculated because of this. This PR fixes that.

Fix references to removed master branch

---

decidim-bulletin_board-app/app/controllers/sandbox/elections_controller.rb
decidim-bulletin_board-app/app/javascript/packs/sandbox/index.js
decidim-bulletin_board-app/app/jobs/sandbox/generate_votes_job.rb
decidim-bulletin_board-app/app/views/sandbox/elections/index.html.erb

Moves the bulk votes generation process to a background job in order to avoid long HTTP requests when generating loads of votes.
To give the user a clue when the job has finished, we show the number of votes currently generated at every page load.
[](https://user-images.githubusercontent.com/5033945/110443193-f1dd8b80-80bb-11eb-93fb-e2fa3b5be5d9.mov)

Move bulk vote generation to background job

---

decidim-bulletin_board-app/app/commands/sandbox/generate_load_test_stats.rb
decidim-bulletin_board-app/app/controllers/sandbox/elections_controller.rb
decidim-bulletin_board-app/app/views/sandbox/elections/index.html.erb
decidim-bulletin_board-app/config/routes.rb

Enables the user to extrapolate some stats from the last load test executed.
Notice that, although the `Sandbox::LoadTestStats` command is prepared to receive a timeframe to run the stats on, for the moment we're only considering the last 2 hours. In the future that could be a user input.
[](https://user-images.githubusercontent.com/5033945/110319548-5989cd00-800f-11eb-84b9-3763236aff11.mov)

Generate load test stats

---

decidim-bulletin_board-app/app/models/election.rb
decidim-bulletin_board-app/app/models/log_entry.rb
decidim-bulletin_board-app/spec/factories/models.rb
decidim-bulletin_board-app/spec/models/log_entry_spec.rb
decidim-bulletin_board-app/spec/queries/get_election_spec.rb
decidim-bulletin_board-ruby/lib/decidim/bulletin_board/authority/create_election.rb
decidim-bulletin_board-ruby/spec/decidim/bulletin_board/authority/create_election_spec.rb

This PR fixes the generation of the chained hashes. We were using the `decoded_data`, which is a ruby hash of hashes (in this case "hash" as dictionary or hashmap, not as string digest), instead of using the `signed_data`, which is a string and much more easy to be calculated equal on different environments.
It also avoid problems when retrieving the previous chained hash when log entries are cached within the election, that were happening during the seed process.
Finally, during the creation of an election it uses the `max_selections` value for the number of answers to select instead of using the total count of answers.

Election fixes: chained_hash generation and election creating

---

decidim-bulletin_board-app/config/initializers/cors.rb
decidim-bulletin_board-app/config/settings.yml
docs/modules/configure/pages/environment_variables.adoc

It doesn't make sense to have a setting for allowed CORS domains. In the future we could add all the authorities domains, but at the moment this PR sets that value to `*`.

Remove unused cors settings

---

bulletin_board/server/app/commands/concerns/log_entry_command.rb
bulletin_board/server/app/models/authority.rb
bulletin_board/server/app/models/bulletin_board.rb
bulletin_board/server/package-lock.json
bulletin_board/server/spec/factories/electionguard.rb
bulletin_board/server/spec/factories/messages.rb

This PR renames the `unique_id` for the `BulletinBoard` to `slug` and sets an `alias` for the `authority.unique_id` to be `authority.slug`. 
It also updates the `electionguard` factories with the latest changes for the `trustee.unique_id`.

Consistent usage of slug instead of unique_id

---

Makefile
bulletin_board/server/cypress/integration/sandbox/election.page.js

In this PR I solve a few problems with the flaky tests (I hope 🤞 ). When performing the tally I'm waiting a few seconds before each trustee starts the process. I also increased the timeout of the cast vote.

Fix e2e flaky test

---

bulletin_board/server/cypress/integration/sandbox/election.page.js

This is another attempt to fix the test flakyness. I tried in #159, but apparently it didn't work. 
The problem is we are receiving "Network errors" while running e2e tests. I suspect that it is something related to the machine running these tests because in my local machine it always works. I'm trying to add some reasonable wait times to make sure it works.

Wait some time before casting the vote while running e2e test suite

---

CHANGELOG.md
Makefile
bulletin_board/js-client/src/vote/vote.component.js
bulletin_board/js-client/src/voter/voter-wrapper-adapter.js
bulletin_board/js-client/src/voter/voter.js
bulletin_board/js-client/src/voter/voter.test.js
bulletin_board/ruby-client/lib/decidim/bulletin_board/authority/create_election.rb
bulletin_board/ruby-client/spec/decidim/bulletin_board/authority/create_election_spec.rb
bulletin_board/server/app/assets/config/manifest.js
bulletin_board/server/app/assets/javascripts/sandbox/elections/new.js
bulletin_board/server/app/assets/javascripts/sandbox/vote.js
bulletin_board/server/app/assets/stylesheets/sandbox/elections/new.scss
bulletin_board/server/app/controllers/sandbox/elections_controller.rb
bulletin_board/server/app/helpers/sandbox/elections_helper.rb
bulletin_board/server/app/views/sandbox/elections/new.html.erb
bulletin_board/server/app/views/sandbox/elections/vote.html.erb
bulletin_board/server/cypress/integration/sandbox/election.page.js
voting_schemes/dummy/js-adapter/src/voter_wrapper.js
voting_schemes/dummy/js-adapter/src/voter_wrapper_adapter.js
voting_schemes/electionguard/js-adapter/src/voter_wrapper_adapter.js
voting_schemes/electionguard/python-wrapper/src/bulletin_board/electionguard/election.py

In this pull request I am using #164 in the frontend part. When voting you can select the ballot style you want to use if any.
I needed to change the sandbox a bit so I added some improvements:
- When creating an election you can add multiple questions.
- When creating an election you can add multiple ballot styles. If you add a question afterwards all ballot styles are updated accordingly.
- When voting you can select the ballot style you want to use.
- When voting you can answer questions using a simple form.
https://user-images.githubusercontent.com/106021/114390619-c9ebb700-9b96-11eb-9b77-1ea05ee3974a.mov
https://user-images.githubusercontent.com/106021/114390999-3c5c9700-9b97-11eb-90c8-fd96232d0d25.mov

Add ballot styles to the voter client

---

CHANGELOG.md
bulletin_board/js-client/package.json

This fixes the bulletin board javascript client so it can be used in `decidim` with `Webpacker`.

Use the correct main file in the bulletin board js client

---

CHANGELOG.md
bulletin_board/ruby-client/lib/decidim/bulletin_board/authority/get_election_results.rb
bulletin_board/ruby-client/spec/decidim/bulletin_board/authority/get_election_results_spec.rb
bulletin_board/server/app/controllers/sandbox/elections_controller.rb
bulletin_board/server/app/views/sandbox/elections/results.html.erb

The ruby client now also asks for the election's verifiable data (the hash and the file's path) with the `get_election_results` query.
This changes slightly the structure of the response, that will need to be adapted in Decidim.
The sandbox has been updated to show the new data retrieved.

Expose verifiable results in get results GraphQL query

---

CHANGELOG.md
bulletin_board/js-client/src/client/__mocks__/graphql-client.js
bulletin_board/js-client/src/client/client.test.js
bulletin_board/js-client/src/client/graphql-client.test.js
bulletin_board/js-client/src/client/operations/get_election_log_entries.gql
bulletin_board/js-client/src/index.js

Now, when querying for `GetElectionLogEntries`, you get the `chainedHash` as well. Also, the `MessageParser` is exported. With that, you can now access the `iat` from Decidim without exposing the whole `decodedData`.
The `chainedHash` will be part of the `Election Log` on Decidim.

Return data for election log

---

.devcontainer/Dockerfile
.dockerignore
.github/workflows/server-workflow.yml
Dockerfile.release
Dockerfile.web

While I was deploying this to `staging` I detected some problems related to the docker base image that includes everything (ruby, node, python and electionguard).
I decided to change its name schema (it's horrible, I know 😅 ) to include all the versions to avoid problems in the future. Previously it was just using the SHA of electionguard commit but if we changed something like the python version the name didn't reflect the change.
Also, I realized that we were including some config data like `.venv` in the docker image mistakenly. This caused some problems while building the docker image in my machine.

Use the correct docker image as base image

---

bulletin_board/ruby-client/lib/decidim/bulletin_board/engine.rb

This PR allows BB to play nice with Decidim when we remove Sprockets dependency (as part of the Webpacker migration) by only loading assets if it's defined.

Only load assets if defined Sprockets

---

.github/workflows/server-workflow.yml
bulletin_board/server/app/models/bulletin_board.rb
bulletin_board/server/spec/models/bulletin_board_spec.rb

We renamed the `unique_id` method to `slug`. Therefore, we got an error when trying to retrieve the `id` of the `client`. This PR adds an `alias` for the `slug` method.

Add alias for unique_id

---

bulletin_board/server/app/services/voting_scheme/dummy/bulletin_board.rb
bulletin_board/server/spec/factories/models.rb
voting_schemes/dummy/js-adapter/src/trustee_wrapper.js
voting_schemes/dummy/js-adapter/src/trustee_wrapper.test.js

This PR fixes some problems with the compensation in the dummy voting scheme:
- It was starting to do things before reaching the quorum.
- It didn't work for all the combinations of number of trustees, quorum and missing trustees.
The new system works like this:
- For each trustee `t`, it calculates it's share: S<sub>`t`</sub> = result * key<sub>`t`</sub>
- When there is at least one missing trustee, the trustees wait until all the active trustees send their shares.
- We will use indexes starting with `m` for missing trustees, and starting with `a` for active trustees.
- Then, the trustees calculate their compensations: C<sub>`at`</sub> = (result<sup>`M`</sup>) / (key<sub>`at`</sub>)<sup>`A`</sup>, where `M` is the number of missing trustees and `A` is number of active trustees.
When the …

Improve dummy compensation procedure

---

Makefile
bulletin_board/server/app/services/voting_scheme/dummy/bulletin_board.rb
bulletin_board/server/cypress/integration/sandbox/election.page.js
bulletin_board/server/cypress/integration/sandbox/election.spec.js
voting_schemes/dummy/js-adapter/src/trustee_wrapper.js
voting_schemes/dummy/js-adapter/src/voter_wrapper.js
voting_schemes/dummy/js-adapter/src/voter_wrapper.test.js

This PR fixes a bug during E2E tests: the correctness of the results were not being checked. This prevented a bug on the results calculation on the dummy voting scheme to be catched. That bug is also fixed on this PR.
Other fixes on the dummy scheme are included in the PR:
* A small typo on the JS client.
* The trustee checks for the quorum before sending the compensation.
* The voters will not use 0 as a random value for "ciphering" the values. This fixes #199.
Finally, the release process was modified to use commit messages without prefixes.

Fix broken check of results during e2e tests
